yangyeom-django/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:user_pk>/', views.detail, name='detail'),
    path('signup/', views.signup, name='signup'),
    # path('login/', views.login, name='login'),
    # path('logout/', views.logout, name='logout'),
    path('<int:user_detail_pk>/follow/', views.follow, name='follow'),
    path('rating/', views.rating, name="rating"),
]

yangyeom-django/movies/urls.py
from django.urls import path
from . import views
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
   openapi.Info(
      title="Movie API",
      default_version='v1',
      description="Movie Info"
   ),
)

app_name = 'movies'

urlpatterns = [
    path('movies/', views.movies_index, name='movies_index'),
    path('movie/<int:movie_pk>/reviews/', views.movie_reviews, name='movie_reviews'),
    path('movies/rating/', views.movies_rating, name="movies_rating"),
    path('movie/<int:movie_pk>/reviews/<int:review_pk>/', views.review_update_delete, name='review_update_delete'),
    path('movie/<int:movie_pk>/', views.movie_detail, name="movie_detail"),
    #=================================================================================
   #  path('<int:movie_pk>/reviews/new/', views.review_create, name='review_create'),
   #  path('<int:movie_pk>/reviews/<int:review_pk>/delete/', views.review_delete, name='review_delete'),
   #  path('<int:movie_pk>/like/', views.like, name='like'),
    path('recommend/', views.recommend, name="recommend"),
    path('evaluatesimi/', views.evaluate_Simi, name="evaluate_Simi"), 

   #  path('test/', views.test, name='test'),

    path('redoc/', schema_view.with_ui('redoc')),
    path('swagger/', schema_view.with_ui('swagger')),
]

yangyeom-django/yangyeomchicken/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_jwt.views import obtain_jwt_token


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('api/v1/', include('movies.urls')),
    path('payments/', include('payments.urls')),

    path('api-token-auth/', obtain_jwt_token),
    path('api-token-auth/registration/', obtain_jwt_token),
]

yangyeom-django/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings

class User(AbstractUser):
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='followings', blank=True)
    similar_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='reference_users', through='Similarity', blank=True)
    # score_total = models.FloatField(default=0)
    score_avg = models.FloatField(default=0)
    paid = models.BooleanField(default=False)

class Similarity(models.Model):
    # 여기서 related_name이 필요한 이유: similarity 값으로 역참조해서 찾을 때 쓰임. 근데 그럴 일 없으니까 아무 이름이나 써도 됨!
    reference_user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="a", on_delete=models.CASCADE)
    similar_user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="b", on_delete=models.CASCADE)
    similarity = models.FloatField(default=0)

yangyeom-django/movies/models.py
from django.db import models
from django.conf import settings


class Genre(models.Model):
    name = models.CharField(max_length=20)


class Movie(models.Model):
    code = models.IntegerField(primary_key=True)
    title = models.CharField(max_length=30)
    poster_url = models.CharField(max_length=140)
    description = models.TextField()
    genres = models.ManyToManyField(Genre, related_name='movies', blank=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_movies')
    watched_users = models.ManyToManyField(settings.AUTH_USER_MODEL, through='Review', related_name='watched_movies')
    score_exp_users = models.ManyToManyField(settings.AUTH_USER_MODEL, through='ScoresExpected', related_name='score_exp_movies')
    score_avg = models.FloatField(default=0)

class Review(models.Model):
    content = models.CharField(max_length=100, blank=True)
    score = models.FloatField()
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


class ScoresExpected(models.Model):
    score = models.FloatField(default=0)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

yangyeom-django/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', )

yangyeom-django/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import get_user_model
# from .forms import CustomUserCreationForm
from django.http import HttpResponse
from django.contrib.auth.forms import AuthenticationForm
# from django.contrib.auth import login as auth_login
# from django.contrib.auth import logout as auth_logout
# from django.contrib.auth.decorators import login_required
from rest_framework.permissions import AllowAny
from rest_framework.decorators import api_view, permission_classes
# from .models import User
from movies.models import Movie, Review
from django.db.models import Avg
from .serializers import UserSerializers
from rest_framework.response import Response


def index(request):
    context = {
        'users' : get_user_model().objects.all()
    }
    return render(request, 'accounts/index.html', context)

@api_view(['GET'])
def detail(request, user_pk):
    user = get_user_model().objects.get(pk=user_pk)
    serializer = UserSerializers(user)
    return Response(serializer.data)


@api_view(['POST'])
@permission_classes([AllowAny])
def signup(request):
    if request.user.is_authenticated:
        return redirect('accounts:index')  # 홈화면으로 돌리기
    if request.method == 'POST':
        user_check = get_user_model().objects.filter(username = request.data['username']).count()
        if user_check == 0:
            get_user_model().objects.create_user(username=request.data['username'], password=request.data['password'])
            return HttpResponse('Saved', status=201)
    return HttpResponse('Unauthorized', status=401)

# def login(request):
#     if request.user.is_authenticated:
#         return redirect('accounts:index')  # 홈화면으로 돌리기
#     if request.method == 'POST':
#         form = AuthenticationForm(request, request.POST)
#         if form.is_valid():
#             auth_login(request, form.get_user())
#             return redirect(request.GET.get('next') or 'accounts:index')  # 홈 화면으로 돌리기
#     else:
#         form = AuthenticationForm()
#     context = {
#         'form': form
#     }
#     return render(request, 'accounts/form.html', context)

# def logout(request):
#     auth_logout(request)
#     return redirect('accounts:index')  # 홈화면으로 돌리기

# @login_required
def follow(request, user_detail_pk):
    user_detail = get_object_or_404(get_user_model(), pk=user_detail_pk)
    user = request.user
    if user != user_detail:
        if user in user_detail.followers.all():
            user_detail.followers.remove(user)
        else:
            user_detail.followers.add(user)
    return redirect('accounts:detail', user_detail_pk)


def rating(request):
    if request.method == 'GET':
        movies = Movie.objects.all()[:30]
        context = {
            'movies': movies
        }
        return render(request, 'accounts/rating.html', context)
    elif request.method == 'POST':
        # user = get_user_model()
        rate_score = 0
        rate_cnt = 0
        for k in request.POST:
            if k == 'csrfmiddlewaretoken':
                continue
            if request.POST[k] == '0':
                continue
            # rate_score += int(request.POST[k])
            # rate_cnt += 1
            movie = get_object_or_404(Movie, pk=k)
            review = Review(user=request.user, movie=movie, score=request.POST[k])
            review.save()
        # request.user.score_total = rate_score
        # request.user.score_avg = rate_score / rate_cnt
        request.user.score_avg = Review.objects.filter(user=request.user).aggregate(Avg('score')).get('score__avg')
        request.user.save()
        
        return redirect('movies:index')

yangyeom-django/accounts/templates/accounts/detail.html
{% extends 'base.html' %}

{% block body %}
<h1>{{ user_detail.username }}님</h1>
<a href="{% url 'accounts:follow' user_detail.pk %}">
  <button class="btn btn-danger">
    {% if user in user_detail.followers.all %}안{% endif %}좋아요
  </button>
</a>

<h2>작성한 평점</h2>
<ul>
  {% for review in user_detail.review_set.all %}
    <li><a href="{% url 'movies:detail' review.movie.pk %}">{{ review.movie.title }}: {{ review.content }} - {{ review.score }}점</a></li>
  {% empty %}
    <li>작성한 평점이 없습니다.</li>
  {% endfor %}
</ul>


<h2>좋아하는 영화</h2>
<ul>
  {% for movie in user_detail.like_movies.all %}
    <li><a href="{% url 'movies:detail' movie.pk %}">{{ movie.title }}</a></li>
  {% empty %}
    <li>좋아하는 영화가 없습니다.</li>
  {% endfor %}
</ul>

<h2>팔로우: {{ user_detail.followings.count }}명, 팔로잉: {{ user_detail.followers.count }}명</h2>
{% endblock %}

yangyeom-django/accounts/templates/accounts/form.html
{% extends 'base.html' %}

{% block body %}
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">확인</button>
</form>
{% endblock %}

yangyeom-django/accounts/templates/accounts/index.html
{% extends 'base.html' %}

{% block body %}
  <h1>User List</h1>
  <ul>
    {% for user in users %}
    <li>
      <a href="{% url 'accounts:detail' user.pk %}">
        {{ user.username }}
      </a>
    </li>
    {% endfor %}
  </ul>
{% endblock %}

yangyeom-django/accounts/templates/accounts/rating.html
{% extends 'base.html' %}
{% block body %}
<div class="container flex-nowrap justify-content-center text-center bg-dark text-light shadow text-shadow">
  <form action="{% url 'accounts:rating' %}" method="POST">
    <div class="row">
      {% csrf_token %}
      {% for movie in movies %}
      <div class="col-3 flex-nowrap shadow mb-5">
        <img style="height:100%;width:100%" src="http://image.tmdb.org/t/p/w500/{{ movie.poster_url }}" alt="">
        <select name="{{ movie.code }}" id="{{ movie.code }}">
          <option value="0">선택안함</option>
          <option value="1">1</option>
          <option value="2">2</option>
          <option value="3">3</option>
          <option value="4">4</option>
          <option value="5">5</option>
        </select>
      </div>
      {% endfor %}
    </div>
    <input type="submit" value="제출">
    </form>
</div>
{% endblock %}